### PR TITLE
[FEATURE] Add a function to rollback an event

### PR DESCRIPTION
**Pull request by mdouchin**
Simple function which "undo" an event by
* deleting a inserted feature
* updating to previous values for changed fields using row data
* insert back a deleted feature 

No complex checks are made, the same as in the replay function. It "just" does the job.

### CODE REVIEW

**Comment by mhugo** [comment]
@mdouchin Thanks !

I wonder if we should constrain the roolback to the last event, since there is no guarantee it will work on a past event. Or we let postgresql raise an exception in this case ?

**Comment by mdouchin** [comment]
> I wonder if we should constrain the roolback to the last event, since there is no guarantee it will work on a past event. Or we let postgresql raise an exception in this case ?

I could not decide for this option or the other. There are drawbacks and advantages in both behaviours... As a safety first change, we could first propose the rollback only for last event. I will change the code to add a check and raise an exception if the event is not the last for the feature

Another question : should we rollback only the changed fields (as it does in my proposal), or UPDATE all the fields to recover the exact status as in row_data ?

**Comment by mhugo** [comment]
> I will change the code to add a check and raise an exception if the event is not the last for the feature

Good !

> should we rollback only the changed fields (as it does in my proposal), or UPDATE all the fields to recover the exact status as in row_data ?

If only the last change is allowed, updating the changed fields should be enough I think ?

**Comment by mdouchin** [comment]
Done and rebased by branch. Please test and report if any issue. I tested it with 2 different datasets ( integer and non integer pkey)

**Comment by mdouchin** [comment]
@mhugo Just rebased and pushed -f to use bigint instead of int for the function parameter

**Comment by mhugo** [comment]
Thanks for your contribution

**Pull request merged**
